---
apiVersion: v1
kind: Service
metadata:
  name: demo-loopback
  labels:
    app: demo-loopback
spec:
  ports:
    - port: 80
      name: demo-loopback
  clusterIP: None
  selector:
    app: demo-loopback

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-loopback-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-loopback
  template:
    metadata:
      labels:
        app: demo-loopback
    spec:
      containers:
        - name: demo-loopback
          image: osixia/phpldapadmin:latest
          ports:
            - containerPort: 80
              name: demo-loopback
---
# demo-loopback route
kind: Route
apiVersion: v1
metadata:
  name: demo-loopback
  labels:
    app: demo-loopback
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: ''
  to:
    kind: Service
    name: demo-loopback
    weight: 100
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
